### PR TITLE
Add contributor panel from Github.

### LINKED ISSUE #11: Add in contributors like underscores.me

### PR DESCRIPTION
**Pull request by sarahmonster**
Work in progress, to fix #11. 

Taking computers to the doctor makes me gun-shy. Will update later this week.

### CODE REVIEW

**Comment by karmatosed** [comment]
Do you still want this open @sarahmonster ?

**Comment by sarahmonster** [comment]
Yep, still WIP; just didn't get time to finish it yet.

**Comment by sarahmonster** [comment]
Finally got around to styling this panel. I'd love to get some eyes/feedback on it!

screen shot 2015-12-21 at 10 28 55 am

I feel like it may need some background texture to give it some interest... maybe transparentised gears or pipes or something patterny?

cc laurelfulford && @alaczek

**Comment by alaczek** [comment]
How about using gears instead of circles? This might turn out to be too much, but it's worth a shot.

**Comment by sarahmonster** [comment]
Quick mockup—not sure this quite works, but I'll try again a little later:

screen shot 2015-12-21 at 10 43 28 am

**Comment by karmatosed** [comment]
I'd maybe suggest adding the cogs is a bit much for the eye. I think the simple border is lovely and really allows the content to stand out. I'd vote against having gears, backgrounds or anything else beyond that border - I think you got it right the first time. That's a dense area content wise and we can't guarantee the complexity visually of avatars. Having the simple treatment allows the eye to navigation without being overwhelmed.

**Comment by sixhours** [comment]
I agree with @karmatosed, the first version looks excellent to me.

**Comment by sarahmonster** [comment]
I've rebased this onto master so it's up-to-date with the most recent changes and merges cleanly. I messed around with gears a bit, but didn't find a solution that worked nicely—I think this iteration is probably the best path forward.

It's merge-able now if anyone would like to review!

**Comment by laurelfulford** [comment]
Overall it looks good! I just noticed this one thing in IE11 (and under, but I think we're less worried about supporting them):

https://cloudup.com/cfx1eiAD5bY

IE really likes having both the height AND width set for SVGs - I think that should fix it!

**Pull request merged**
