### PR TITLE
Better gears

### LINKED ISSUE #13: Fancy-pants gears
This gear is a bit awkward—a nicer effect would be using three, with more detail, and better-designed. 

screen shot 2015-11-21 at 16 16 21

### PR DESCRIPTION
**Pull request by sarahmonster**
Related to/in conjunction with work on #15. This fixes #13 by sprucing up the gears on the base panel. I'm not sure they feel 100% right just yet, so I'm open to critique/suggestions prior to merging! :8ball: 

screen shot 2015-12-02 at 01 09 34

screen shot 2015-12-02 at 01 14 50

### CODE REVIEW

**Comment by laurelfulford** [comment]
I really like the second, non-transparent gears in the 'Just the basics' section. The level of details is a lot better for their scale.

For placement -- it seems like there's a really big gap between the gears on the left and the text on the right. I like how the gears pop out on the left; not sure if there's an easy way to close the gap without pulling in the gears, or making the text so wide it's tricky to read. 

For the conveyor belt bit -- I feel like the 'teeth' might be a bit too wide on the new gears compared to the others throughout the theme. What do you think about making them a bit narrower?

**Comment by sarahmonster** [comment]
Good call! I've revised the gears a bunch and have improved some other stuff while I was in there. I'm still not sure about the colour. I almost wonder if they need an outline or something.... 

Considered doing some motion as but I don't know if that'd be too much—it might be overkill with so much already moving on the page. 

They feel a bit flat to me, like they need something else:

screen shot 2015-12-05 at 12 15 36 am

But if nothing else, this is at least "better than what we had before," which may mean it's time to merge, then iterate later with fresh :eyeglasses:

**Comment by sixhours** [comment]
Merge that puppy, IMO!

**Comment by laurelfulford** [comment]
:heart: :heart: :heart: 

I noticed there's one minor issue in Chrome - the gears underlap the text below quite a bit. 

Gears mcgee

It's pretty minor, but I didn't think it was intentional. It doesn't cause any legibility issues, though, so let me know if you'd like me to merge this anyway, and it can be adjusted in future versions. Thanks!

**Pull request merged**
