### PR TITLE
Change targeted theme name in generator to match new name

### PR DESCRIPTION
**Pull request by davidakennedy**
This changes all the function names, package headers, text domains, etc. to match the agreed upon name, and ensures the generator works properly with the theme components.

### CODE REVIEW

**Comment by sarahmonster** [comment]
If you enter a theme name with an apostrophe—for instance `It's_Tricky` the output is escaped like so: `It\'s_Tricky`. 

In related news, I am currently listening to Run-D.M.C. :musical_note:

**Comment by sarahmonster** [comment]
The primary theme JS should either be called something annoyingly vague like `main.js` or renamed by the generator:

`wp_enqueue_script( 'its-tricky', get_template_directory_uri() . '/assets/js/thememodern.js', array(), '20120206', true );`

Also, should it be enqueued as `its-tricky-js` to retain consistency with other scripts/styles?

**Comment by sarahmonster** [comment]
readme.txt is using the description, but isn't replacing the theme title:

```
=== components ===

Contributors: automattic
Tags: translation-ready, custom-background, theme-options, custom-menu, post-formats, threaded-comments

Requires at least: 4.0
Tested up to: 4.2.2
Stable tag: 1.0.0
License: GPLv2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html

A starter theme called components, or underscores.

== Description ==

This is the greatest theme in the universe.

== Installation ==

1. In your admin panel, go to Appearance > Themes and click the Add New button.
2. Click Upload and Choose File, then select the theme's .zip file. Click Install Now.
3. Click Activate to use your new theme right away.

== Frequently Asked Questions ==

= Does this theme support any plugins? =

components includes support for Infinite Scroll in Jetpack.
```

We may also want to adjust the content of this since bits of it don't seem super relevant; see https://github.com/Automattic/theme-pattern-library/issues/124

**Comment by sarahmonster** [comment]
rtl.css needs this line replaced:

`Theme Name: components`

**Comment by sarahmonster** [comment]
POT file isn't replacing strings properly; might be fixed by https://github.com/Automattic/theme-pattern-library/pull/129 but would require double-checking once that's merged.

**Comment by sarahmonster** [comment]
Pretty minor, but `jetpack.php` isn't replacing this line properly:

`* @since components 1.0`

**Comment by sarahmonster** [comment]
I generated two themes last night (modern blog and business), and looked through every file to find text domain issues. What I've found I've posted to the various repos or as comments here. Overall, looks like it's going really well—there are just a few places where things could be improved. :)

**Comment by davidakennedy** [comment]
I fixed the apostrophe thing here: https://github.com/davidakennedy/components.underscores.me/commit/676a9ff5e33ae05e6adc7e61ae215371d89474b0

The `@since` stuff is also fixed, as is the `.js` file name in the modern blog branch.

The rest can be fixed by capitalizing `components` where necessary so the generator can pick up on it.

**Comment by sarahmonster** [comment]
Merging now since the readme is a separate issue and the capitalisation (https://github.com/Automattic/theme-pattern-library/issues/141) will fix everything else.

**Pull request merged**
