### PR TITLE
34 code review changes

### LINKED ISSUE #34: PHP Code review
Let's get a full code review from another developer.

### PR DESCRIPTION
**Pull request by jeffikus**
Here's a PR with my review changes, I moved theme-types into a function in case we ever want to make it dynamic from a database call (instead of a file) we would just need to remove the file require, and do the db call.

I have a few additional queries though:

**1) front-page.php**
- Why are we using file_get_contents() instead of WP_Filesystem?
- There is 1 instance of a different text domain on line 108, not sure why this is the case:
  $contributions = sprintf( '%d %s', $contributor->contributions, _n( 'contribution', 'contributions', $contributor->contributions ) );

**(2) components-generator.php**
- In _get_types()_ function, why is $types declared as static, when it's immediately changed?

_General_
- There are a number of large functions. Perhaps we should refactor and split up? Or at least add some additional logging inside the larger functions. 
- The syntax is good, but it always depends how pedantic we want to be? :) Checking for every type etc.
- I noticed in some instances, function args have default values, while other don't.

_[Lines 868-880](https://github.com/Automattic/components.underscores.me/blob/34_code_review_changes/inc/components-generator.php#L868-L880)_
- The nested foreach loops here make me a little nervous, as this is just before the zip is delivered. We want to know if things break here so I would definitely add some logging at this point. Especially as we don't know how this loop will handle under scale.

_[Lines 872-875](https://github.com/Automattic/components.underscores.me/blob/34_code_review_changes/inc/components-generator.php#L872-L875)_
- Are there missing braces here, or supposed to be like this?

Otherwise it's looking great! Nice work guys!

Closes #34

### CODE REVIEW

**Comment by mendezcode** [comment]
``` php
public function get_types() {
    static $types;
    if ( ! isset( $types ) ) {
        $types = $this->read_json( $this->build_dir . '/types.json' );
        // Prepend Base theme data to the $types array.
        // It isn't a type, but should still be included in the generator processes.
        $types = array_merge( array( 'base' => 'Base' ), $types );
    }
    return $types;
}
```

---

> In get_types() function, why is $types declared as static, when it's immediately changed?

In this particular case, `$types` is declared as a [PHP Static Variable](http://php.net/manual/en/language.variables.scope.php#language.variables.scope.static), which means it will retain its value in subsequent function calls.

The reason for this is because we don't want to be reading the JSON file each time we call this function, instead we save it in a static (cached) variable, which gets returned each time the function is called, improving performance.

Being static allows for `$types` to be assigned only once (that is, on the very first function call of `get_types()`, in which the condition of `! isset( $types )`  returns true.

**Comment by davidakennedy** [comment]
Hey @jeffikus, thanks for the questions and PR! Here are the answers below so you can adjust things:

> Why are we using file_get_contents() instead of WP_Filesystem?

I think we just went with native PHP functionality first. If WP_Filesystem makes me sense, has more advantages and works, I don't see why we couldn't use it.

> There is 1 instance of a different text domain on line 108, not sure why this is the case:

That looks like a typo or copy and paste error – it should match the rest of the theme.

> General

All these are great suggestions, and maybe we make a separate issue for code improvements. This initial review is really more about major issues. I think the reason some of the functions got out of head was that we planned its architecture, but had to make changes based on needed functionality we didn't foresee. To meet our deadline, we kept building. 😄  But now, we can start making it more optimal and pretty.

> Lines 868-880

Sure – I'd be open to changes here. That particular code was pulled from the generator on underscores.me, so it's battle tested in a sense. But we could always do better.

> Lines 872-875

That's poor code on my part. There should be braces there.

Thanks again for the great, thorough review!

**Comment by jeffikus** [comment]
@mendezcode thanks for clarifying, I guess I was just wondering why it wasn't a class level variable then.

@davidakennedy I've added the missing text domain and the braces, happy to move the other questions into separate issues for refactor :)

You can merge if you are happy! Looking good guys!

**Comment by davidakennedy** [comment]
@jeffikus Made one small tweak here: https://github.com/Automattic/components.underscores.me/pull/154/commits/6d65a58c29b6a55beecdc077c06d51c2bd98c239

I don't think we need the function checks there because we could use `wp_dequeue_script` to modify things. If there's a reason I'm not thinking of that the previous way was better, let me know. 😄

**Comment by jeffikus** [comment]
@davidakennedy that makes sense :)

**Pull request merged**
