### PR TITLE
Updating JS so form no longer opens all over the page

### PR DESCRIPTION
**Pull request by laurelfulford**
Update for #72.

I agree that the form opening all over feels a bit... wiggy? This update removes that functionality from the JS so clicking the 'Build' button will just bring you down to the form under the types instead. 

The radio buttons still update to reflect the type you clicked.

### CODE REVIEW

**Comment by laurelfulford** [comment]
I should have said - comments/feedback/thoughts on this are very welcome! Please compare the behaviour to http://components.underscores.me/ and chime in!

**Comment by sarahmonster** [comment]
This feels SO much better. 

It might be nice to make it super-clear that we're magically selecting the right type for the user—what about a visual indicator that the type selection has changed when we get down to the form—maybe flashing the text and/or the radio input? (Transitioning from a scale of 0 to 100 with a little elasticy bounce maybe?)

**Comment by alaczek** [comment]
This makes much more sense! 

> what about a visual indicator that the type selection has changed

That feels a bit over the top to me, I'd leave it as is, at least for now.

**Comment by davidakennedy** [comment]
I think this is ready and simplifies things a lot. @sarahmonster your feedback about an indicator is something we should think about as a future enhancement.

**Pull request merged**
